<?xml version="1.0" encoding="utf-8"?><Database Name="newdb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=station1\;Initial Catalog=newdb;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="newdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.emptable" Member="emptables">
    <Type Name="emptable">
      <Column Name="Empid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Empname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>